### ISSUE TITLE
在tomcat中使用awacs无数据

### ISSUE THREAD

**Issue by tao100** [Archerfeel/awacs#10]
在Web容器Tomcat中使用AWACS时，Javaagent已成功Connect `Server，当有http请求时，mongodb中不会产生新的数据，但当用Javaagent去监测awacs-demo.jar时，却会产生数据，如何解决？

**以下为Tomcat加载agent截图：**
![Image of Yaktocat](http://images.cnblogs.com/cnblogs_com/beautiful-code/970061/o_QQ%E6%88%AA%E5%9B%BE20170321100720.png)

**Comment by tao100** [comment]
该项目是在Windows下开发的，还是Linux？能否将开发环境描述一下，方便搭建环境，谢谢？

**Comment by ArcherFeel** [comment]
statcktrace插件目前只支持spring的应用, 插件会寻找@Controller或者@RestController的类, 并且从带有@RequestMapping的方法为起点对方法调用栈逐个方法做修改.
这部分目前适配得不是很广泛, 如果不是使用springmvc, 就无法找到调用栈起点. 欢迎PR

**Comment by tao100** [comment]
我们的测试项目是基于springmvc，采用注解的方式拦截请求，目前在Tomcat中使用时，没有数据，只有执行awacs-demo才会有数据产生，不知道原因为何？

**Comment by ArcherFeel** [comment]
在awacs.properties配置中修改包名前缀
`awacs.plugins.stacktrace.pluginProperties.packagePrefix = io.awacs.demo` 改为你们测试项目的包名前缀
`awacs.plugins.stacktrace.pluginProperties.packagePrefix = com.xx.yy`

BTW, 如果程序能够处理的自定义异常, 可以修改
`awacs.plugins.stacktrace.handlerProperties.notification.excludeExceptionPrefix = io.awacs.demo`
配置之后, 特定的异常不会触发邮件报警(典型的如参数错误), 而只报警未期待的异常
